[package]
name = "proto-renumber"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ProtoRenumber"
path = "src/main.rs"

[dependencies]
regex = "*"
clap = "*"

[profile.release]
lto = true
strip = true
panic = "abort"
codegen-units = 1
